# Generated by Django 5.2.7 on 2025-10-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=150)),
                ("matricula", models.CharField(max_length=11, unique=True)),
                ("funcao", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                        default="Ativo",
                        max_length=10,
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
